### ISSUE TITLE
taking very long time

### ISSUE THREAD

**Issue by Egalite123** [rodrigopivi/Chatito#27]
Hi, After installing 2.0, for a decently large dataset it is taking much longer than the earlier version (for the same file). 
Same problem on the online too. Page times out.
Anyone have similar experiences?

**Comment by rodrigopivi** [comment]
hi @Egalite123,

can you post your example? and how many examples you need?

**Comment by rodrigopivi** [comment]
Just released v2.1.0, now the online ide by default prevents generating datasets that don't specify the training and testing examples required... maybe it was taking too much time for you because the dataset was too big to be handled in a simple way. for very very large datasets the npm package with default adapter should work since it uses file streams. let me know if the new version or the npm package  fixes your large dataset issue. closing the ticket for now, feel free to reopen if still having this issue.

**Comment by suenpun** [comment]
40,000 examples it seems like its stuck.one intention better less than 1000 examles under my testting

**Comment by suenpun** [comment]
and  another question :how to generate the regex template in the format of rasa? Is there this function?
