### ISSUE TITLE
how to control the data generation

### ISSUE THREAD

**Issue by githubclj** [rodrigopivi/Chatito#28]
when i use the same pattern and generate 100 samples, whether it can make sure that the data genereated always  be same everytime i runs the generate and download the rasa_nlu data

**Comment by rodrigopivi** [comment]
hi @githubclj, interesting idea but its not something we want to implement because if we go that way we will need to always generate all possible combinations for a dataset. The firsts versions of chatito used to work that way, but for large datasets it just takes too much time to generate all combinations and if i don't generate all combinations, the utterances at the end of the generation process would never be seen. If you really need to have the same dataset, you can try to generate all possible combinations, the data will contain the same amount of examples each time but with different order. Just be aware that it is not recommended to generate all combinations.

Chatito takes ideas from probabilistic programming languages, and the idea is that the utterances are pulled from a cloud of probabilities on demand, and since we can pull a subset of all the possibilities, we need them to be a random sample, hope this makes it clear why this feature is not going to be implemented.
