### ISSUE TITLE
Using a folder of chatio files fails because of the MergeDeep function 

### ISSUE THREAD

**Issue by hao-fang** [rodrigopivi/Chatito#33]
The MergeDeep function (Chatito/src/utils.ts) does not work for this scenario since the "common_examples" field is an array. But the MergeDeep function does not merge arrays.  So only the last file in a directory is kept.
I found the example in https://github.com/saikojosh/Object-Assign-Deep which seems to explain the behavior.

**Comment by rodrigopivi** [comment]
hi @hao-fang 

Yes, this issue was reported 2 days ago here https://github.com/rodrigopivi/Chatito/issues/31

Since then the issue was fixed with the 2.1.4 release, also added some tests for that use case:

https://github.com/rodrigopivi/Chatito/blob/master/src/tests/bin.spec.ts#L147-L177

Please let me know what npm package version you are using. Thanks!

**Comment by hao-fang** [comment]
Thanks! I was using 2.1.3 and didn't notice there is a new version.
I've upgraded my package. Thanks!

Best,
Hao
