### ISSUE TITLE
Ability to generate maximum count of training examples

### ISSUE THREAD

**Issue by spiralswimmer** [rodrigopivi/Chatito#62]
I need to automate generation of the training data, however I want to include maximum possible examples for my entities rather than give an arbitrary number per intent. Currently the code will fail saying n examples can't be generated, any way to make it generate the maximum possible in this case?

**Comment by rodrigopivi** [comment]
@spiralswimmer if you youse the CLI tool, and don't pass 'training' or 'testing' arguments it will try to generate all variations, currently this is only supported at the CLI tool and it may stop when reaching a max number of duplicates.

**Comment by khalo-sa** [comment]
hi @rodrigopivi , I'm not sure if you understood @spiralswimmer 's point. At least I feel like I'm facing the same (little) problem. I like to specifiy the number of training examples per intent in order to prevent overfitting during training:
`%[intent]('training': '50')`
For most of my intents this works just fine since the number of samples that can be generated exceeds my limit of 50. However, some of my intents can only generate less than 50. When starting the generation script I'm facing errors like 'Can't generate 50 examples. Max possible examples is 34'.
Now, instead of having to manually fix this by removing the '('training': '50')' command from the intent, I would prefer to have a flag which, if set, doesn't stop the generation script but rather informs me about the impossibility to generate 50 examples, and generates the maximally possible number (34) instead.

**Comment by rodrigopivi** [comment]
@khalo-sa Yes that may be a good addition for future releases, keeping the issue open.

**Comment by rodrigopivi** [comment]
@khalo-sa, have you tried to not specify the training argument? just e.g.: `%[intent]`

**Comment by khalo-sa** [comment]
> @khalo-sa, have you tried to not specify the training argument? just e.g.: `%[intent]`

hi rodrigo. yes, I prefer to do that when facing the 'Max possible examples' error instead of setting the limit to the exact max possible number. Still, manual editing of the chatito file is necessary either way.

**Comment by rodrigopivi** [comment]
Fixed in 2.3.0.
