### ISSUE TITLE
Performance issues when generating all variations

### ISSUE THREAD

**Issue by andrewpstern** [rodrigopivi/Chatito#64]
Hi Rodrigo,

Thank you for developing Chatito, it's very useful.

I'm using Chatito to generate a complete set of variations for a definition file (not the normal use-case for Rasa, I know.)  Chatito successfully does this when I leave out training/testing specifications in intents.

However on what seems like a simple intent, it's taking multiple minutes to do the generation.  I'm running on a modern MacBook Pro.

I've attached my definition file with 2 intents in it. It takes about 3 minutes to generate the results - 810 variations for intent 1, and 7992 variations for intent 2.

If I only run intent 1, it takes about 2 seconds.  So intent 2 is the problem.  I'm doing some nesting, but it's unclear why it's causing this degree of performance problems.

Any ideas?

thanks
Andrew

[test.chatito.txt](https://github.com/rodrigopivi/Chatito/files/2963332/test.chatito.txt)

**Comment by rodrigopivi** [comment]
Hi @andrewpstern ,

The problem is that the current implementation is not optimized to generate all variations, so when you try to generate all, it will just calculate a total of max examples, and try to reach it, if too many duplicates then it may exit before reaching that number, so it is highly recommended that you limit the generation using training and testing arguments. I don't see a practical use case for having to generate all variations.

Hoping to optimize this too in the next versions. Thanks

**Comment by rodrigopivi** [comment]
Now it's possible to control the generator path's probability, that in combination with training and testing arguments to limit the output size should be enough to prevent this problem. Also it is recommended to specify the training and testing arguments.
