### ISSUE TITLE
Unhandled crash when generating testing data

### ISSUE THREAD

**Issue by hinca** [rodrigopivi/Chatito#66]
Hi Rodrigo, I'm having an ungraceful crash when trying to generate training data on v2.1.5.

> $ npx chatito chatito\nluData.txt--format=rasa --outputPath nlu-training-test
> Processing file: chatito\nluData.txt
> TypeError: Cannot read property 'value' of undefined
>     at data.reduce (npm\node_modules\chatito\dist\main.js:31:54)
>     at Array.reduce (<anonymous>)
>     at chatitoFormatPostProcess (npm\node_modules\chatito\dist\main.js:14:22)
>     at Object.<anonymous> (npm\node_modules\chatito\dist\main.js:214:31)
>     at Generator.next (<anonymous>)
>     at fulfilled (npm\node_modules\chatito\dist\main.js:4:58)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
>     at findNodeScript.then.existing (nodejs\node_modules\npm\node_modules\libnpx\index.js:268:14)
> FULL ERROR REPORT:
> TypeError: Cannot read property 'value' of undefined
>     at data.reduce (npm\node_modules\chatito\dist\main.js:31:54)
>     at Array.reduce (<anonymous>)
>     at chatitoFormatPostProcess (npm\node_modules\chatito\dist\main.js:14:22)
>     at Object.<anonymous> (npm\node_modules\chatito\dist\main.js:214:31)
>     at Generator.next (<anonymous>)
>     at fulfilled (npm\node_modules\chatito\dist\main.js:4:58)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
>     at findNodeScript.then.existing (nodejs\node_modules\npm\node_modules\libnpx\index.js:268:14)

This might be an issue with the attached data, which in any case validates fine in the online tool, but it is really difficult to tell from this generic error. Is there a way at least to debug or enable logging, in order to get more meaningful error output?

Adjusting the training and/or testing amount does not seem to influence this behavior.

What is interesting is that the behaviour seems to be somewhat non-deterministic, some runs succeed, but some fail with the above. This indicates that some of the generated options that don't get generated all the time cause the problem. 

[nluData.txt](https://github.com/rodrigopivi/Chatito/files/3116878/nluData.txt)

**Comment by rodrigopivi** [comment]
Hi @hinca,

Thanks for the report. You should try to split your intentions into files, makes it easier to debug and maintain but also will soon improve logging for the library too. This particular case you are reporting is because you are declaring this block:

```
%[get_bodypart]('training': '4000', 'testing': '5')
    ~[bodypart_join?] ~[bodypart_prefix?] @[bodypart?] ~[bodypart_suffix?]
    ~[bodypart_prefix?] @[bodypart?] ~[bodypart_suffix?]
```

All the sentences defined inside `get_bodypart` are optional (because of the `?`) symbol at the end, so as the generator tries to get sentences, there are some cases where the generated text will be empty and an empty string cannot map to any intention. It is required that all sentences return some text, and if all entities are optional that may not be the case for all scenarios.

Will keep this issue open to remember to improve the error message for this use case. As a quick fix, try to use this block instead (to make `bodypart` slot as non optional):

```
%[get_bodypart]('training': '4000', 'testing': '5')
    ~[bodypart_join?] ~[bodypart_prefix?] @[bodypart] ~[bodypart_suffix?]
    ~[bodypart_prefix?] @[bodypart] ~[bodypart_suffix?]
```

**Comment by hinca** [comment]
Thanks for the heads-up, that is obviously an input data mistake. Bonus points if it's handled gracefully later.

**Comment by rodrigopivi** [comment]
This crash is now handled gracefully in v2.2.0, cheers.
